apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: mylivenessprobe
spec:
  containers:
  - name: liveness
    image: ubuntu
    command: ["/bin/sh","-c","touch /tmp/healthy; sleep 1000"]
    livenessProbe:
      exec:
        command: ["/bin/sh","-c","cat /tmp/healthy"]
      initialDelaySeconds: 5
      periodSeconds: 2
      timeoutSeconds: 2
