apiVersion: v1
kind: Pod
metadata:
  name: myvolemptydir
spec:
  containers:
  - name: centos1
    image: centos
    command: ["/bin/bash", "-c", "sleep 15000"]
    volumeMounts:                 
      - name: xchange
        mountPath: "/xchange"          
  - name: centos2
    image: centos
    command: ["/bin/bash", "-c", "sleep 10000"]
    volumeMounts:
      - name: xchange
        mountPath: "/tmp/data"
  volumes:                                                   
  - name: xchange
    emptyDir: {}
