apiVersion: v1
kind: Pod
metadata:
  name: myvolhostpath
spec:
  containers:
  - name: os1
    image: centos
    command: ["/bin/bash", "-c", "sleep 15000"]
    volumeMounts:
    - mountPath: /hostpath
      name: testvolume
  volumes:
  - name: testvolume
    hostPath:
      path: /data
